### ISSUE TITLE
大佬，是不是不能用了

### ISSUE THREAD

**Issue by gittkt** [Mask0913/Ayit_library#6]
从昨天就预约不到了，求更新

**Comment by Mask0913** [comment]
已经更新了&nbsp;可以使用了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mask0913/Ayit_library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 晚上10:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Mask0913/Ayit_library] 大佬，是不是不能用了 (#6)





 
Closed #6.
